services:
  nextjs:
    container_name: nextjs
    # image: ronnienayak/save-up-nextjs
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app_network:

volumes:
  pgdata:
