import { Sidebar } from "@repo/ui/src";
import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="text-white">
      <body className={inter.className}>
        <div className="flex text-white bg-[#121e2c] font-bold">
          <Sidebar />
          {children}
        </div>
      </body>
    </html >
  );
}
